language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 3.0
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
notifications:
  email:
    on_success: never
    on_failure: always
