language: csharp
dist: xenial
sudo: required
mono: none
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
notifications:
  email:
    on_success: never
    on_failure: always